<a href="https://colab.research.google.com/github/JuliaRenovato/Projeto123/blob/main/PRO_C126_Project_Boilerplate_Code(pt).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

O **Tiro com Arco** é um jogo em que os jogadores atiram flechas de ponta afiada em um alvo redondo com 10 anéis.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/4de9132a-c71d-42ce-9099-3293e8805fd9.jpg">

## Problema de Aprendizado por Reforço (RL) a Resolver
Acerte o centro do alvo que proporciona a recompensa máxima

<img src="https://s3-whjr-curriculum-uploads.whjr.online/40656a8c-14e2-4dd7-9f9e-4c17669b9182.png" width=300>


Número de **Estados**: ?

Número de **Ações**: ?



In [ ]:
#Importe as bibliotecas
import numpy as np
import random

## Matriz de Recompensas
A Matriz de Recompensas representa os estados como linhas e as ações como colunas com os respectivos valores de recompensas atribuídos a um determinado par de estado e ação.

In [ ]:
#Crie a matriz de recompensas
rewards = np.array([10,9,8,7,6,5,4,3,2,1])
print(rewards)

[10  9  8  7  6  5  4  3  2  1]


## Execute Ações Aleatoriamente

In [ ]:
#Defina shoot()
def shoot():
  return np.random.randint(0,10)

In [ ]:
action = shoot()
print(action)

8


##Matriz Q
O **Aprendizado Q** é um algoritmo de aprendizado por reforço. Dado o estado atual, ele ajuda a encontrar a melhor ação a ser tomada pelo agente.

A **Matriz Q** representa a recompensa recebida após uma ação específica no estado atual. Inicialmente, todos os elementos da matriz Q estão zerados.


In [18]:
#Crie a matriz Q
q_matrix = np.zeros([10])
print(q_matrix)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##Execute uma Ação

In [19]:
#Defina take_action

def take_action(reward_matrix):

     #Chame a função shoot() para obter a ação
     action = shoot()

     #Imprima a ação
     print(action)

     #Obtenha a recompensa correspondente usando a matriz de recompensas
     reward = reward_matrix[action]

     #Imprima a recompensa
     print(reward)

     return action, reward

In [22]:
action, reward = take_action(rewards)
print(reward)

1
9
9


## Atualize a Matriz Q

In [34]:
#Defina o método run_episode()

def run_episode(reward_matrix, shoot_per_game=5):

  score = 0

  #use o loop for para percorrer o número de tentativas
  for shoot_number in range(shoot_per_game):

        #imprima o número do tiro
        print(shoot_number)

        #chame o método take_action para obter a ação
        action, reward = take_action(reward_matrix)

        #aumente a pontuação
        score = score + reward_matrix[action]

        #imprima o número do tiro final
        print(shoot_number)

    #Atualize a matriz Q
        q_matrix[action] = q_matrix[action]+score+5

        print("Matriz Q ","\n", q_matrix)


  new_state = action

  #retorne a matriz Q atualizada
  return q_matrix

In [35]:
#Chame o método run_episode para verificar a matriz Q final de um episódio
q_table = run_episode(rewards)
print(q_table)

0
0
10
0
Matriz Q  
 [15.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
1
5
5
1
Matriz Q  
 [15.  0.  0.  0.  0. 20.  0.  0.  0.  0.]
2
8
2
2
Matriz Q  
 [15.  0.  0.  0.  0. 20.  0.  0. 22.  0.]
3
7
3
3
Matriz Q  
 [15.  0.  0.  0.  0. 20.  0. 25. 22.  0.]
4
2
8
4
Matriz Q  
 [15.  0. 33.  0.  0. 20.  0. 25. 22.  0.]
[15.  0. 33.  0.  0. 20.  0. 25. 22.  0.]


## Treinar

Crie uma função que execute um número de jogos, execute cada jogo por um determinado número de vezes e calcule as recompensas médias para cada vez.

In [45]:
#Defina a função train()

def train(episodes):
  #Use o loop for para percorrer os episódio
  for episode in range(episodes):
    #Inicialize a variável total_reward

    total_reward = 0
    #Imprima "Episódio Inicia" com o número do episódio
    print(episode)

    #Chame o método run_episode() para obter a matriz q de um episódio
    episode_q_matrix = run_episode(rewards)

    #A recompensa do episódio será a soma de todas as recompensas de um episódio
    reward_episode = sum(episode_q_matrix)
    print(reward_episode)

    #imprima a recompensa do episódio


    #A recompensa total será a soma de todas as recompensas do episódio
    total_reward = total_reward+reward_episode

  #retorne total_reward
  return total_reward

##Treine 1000 episódios

In [46]:
#Execute a função train() para 1000 episódios
number_of_episodes = 1000
variavel = train(number_of_episodes)

#Imprima a recompensa média
print(variavel)

A saída de streaming foi truncada nas últimas 5000 linhas.
4
1
9
4
Matriz Q  
 [10562. 10081. 10485.  9899.  9698.  8719.  8083.  7793.  7950.  6849.]
90119.0
844
0
3
7
0
Matriz Q  
 [10562. 10081. 10485.  9911.  9698.  8719.  8083.  7793.  7950.  6849.]
1
3
7
1
Matriz Q  
 [10562. 10081. 10485.  9930.  9698.  8719.  8083.  7793.  7950.  6849.]
2
8
2
2
Matriz Q  
 [10562. 10081. 10485.  9930.  9698.  8719.  8083.  7793.  7971.  6849.]
3
3
7
3
Matriz Q  
 [10562. 10081. 10485.  9958.  9698.  8719.  8083.  7793.  7971.  6849.]
4
4
6
4
Matriz Q  
 [10562. 10081. 10485.  9958.  9732.  8719.  8083.  7793.  7971.  6849.]
90233.0
845
0
4
6
0
Matriz Q  
 [10562. 10081. 10485.  9958.  9743.  8719.  8083.  7793.  7971.  6849.]
1
2
8
1
Matriz Q  
 [10562. 10081. 10504.  9958.  9743.  8719.  8083.  7793.  7971.  6849.]
2
6
4
2
Matriz Q  
 [10562. 10081. 10504.  9958.  9743.  8719.  8106.  7793.  7971.  6849.]
3
0
10
3
Matriz Q  
 [10595. 10081. 10504.  9958.  9743.  8719.  8106.  7793.  7971.  684

## Conclusão:

Isso nos dá uma boa ideia sobre o desempenho geral do aprendizado de reforço mais simples com o problema **um estado - múltiplas ações**, também conhecido como problema "**K-Armed Bandit**".

Um dos principais casos de uso desse tipo de problema pode ser visto na seleção do anúncio certo entre muitos a serem exibidos na página web. A máquina pode ser ensinada a escolher o melhor anúncio com mais cliques do usuário!!

